# Generated by Django 4.1.3 on 2022-11-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=127, verbose_name='Наименование клиента')),
                ('client_org', models.CharField(max_length=255, verbose_name='Наименование клиентской организации')),
                ('number', models.IntegerField(verbose_name='Номер счета')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('service', models.CharField(max_length=255, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
