# Generated by Django 4.1.3 on 2022-11-23 22:36

import bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='service',
            field=models.CharField(max_length=255, validators=[bills.models.validate_service], verbose_name='Услуга'),
        ),
    ]
